---
- name: Install Homebrew packages
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    brew_packages:
      - skopeo
      - awscli
      - jq
      - direnv
      - tree
      - neovim
      - fzf
      - gnupg
      - just
      - fwdcloudsec/granted/granted
      - grype
      - syft
      - pre-commit
      - mysql-client@8.4
      - trufflehog

    brew_casks:
      - session-manager-plugin

  tasks:
    - name: Install packages via Homebrew
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ brew_packages }}"

    - name: Install casks via Homebrew
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: present
      loop: "{{ brew_casks }}"
